### ISSUE TITLE
Please update `kernel32-sys` in dependencies

### ISSUE THREAD

**Issue by zonyitoo** [rust-lang-deprecated/time#126]
Currently `time` depends on `kernel32-sys 0.1.2` and most of the libraries are now using `^0.2`, so please update it to `^0.1.2`.

**Comment by BurntSushi** [comment]
To be clear, it seems that `kernel32-sys` will completely stop a build if both a `0.1.x` and a `0.2.x` version are in the list of dependencies.

cc @retep998

**Comment by zonyitoo** [comment]
Yes, I have already encountered the build issue of dependencies conflict.

**Comment by retep998** [comment]
Oh dear, that `links = "kernel32"` thing...

This is awful. If I need to make breaking changes, I have to publish a new major version to avoid breaking stuff. But if I publish a new major version, it breaks things. This is just ridiculous.

cc @alexcrichton
