### ISSUE TITLE
Add `impl Into<std::time::Duration> for time::Duration` ?

### ISSUE THREAD

**Issue by dpc** [rust-lang-deprecated/time#128]
I need a way to convert time::Duration to std::time::Duration, now that it's stable.

Maybe `From` would be useful too.

**Comment by jpastuszek** [comment]
This is what I do in my code (not sure if correct):
```
std::time::Duration::new(
            duration.num_seconds() as u64,
            (duration.num_nanoseconds().expect("sleep duration too large") - duration.num_seconds() * 1_000_000_000) as u32
        ))
```
Since fields and nanos_mod_sec() are private I guess I will not be able to get full possible range after this conversion...

**Comment by tailhook** [comment]
I want this too far too often. Should I make a pool request or is it a banned feature for some reason?

**Comment by alexcrichton** [comment]
Nah feel free to send a PR!
