### ISSUE TITLE
Update libc >= 0.2.3

### ISSUE THREAD

**Issue by emoon** [rust-lang-deprecated/time#130]
Hi,

When building one of my projects (with Rust 1.6) that depend on the time crate I get this warning

```
github.com-88ac128001ac3a9a/libc-0.2.2/src/lib.rs:13:21: 13:39 warning: lint raw_pointer_derive has been removed: using derive with raw pointers is ok
github.com-88ac128001ac3a9a/libc-0.2.2/src/lib.rs:13 #![allow(bad_style, raw_pointer_derive, overflowing_literals, improper_types)]
```

Now this is only a warning but I think it would be nice if the time crate could use a newer version of libc where this warning has been fixed.

**Comment by alexcrichton** [comment]
Thanks for the report! I believe that if you issue a `cargo update -p libc` it should work just fine, however, as this library will automatically pick up newer versions of the `libc` crate. The dependency information currently says that it's compatible with the entire `0.2.x` series of `libc`

**Comment by emoon** [comment]
Ah. I see. Thanks!
